### ISSUE TITLE
다들 잘 지내시나요...?

### ISSUE THREAD

**Issue by keeprainy** [boostcamp-ai-tech-4/coding-test-study#371]
제가 속한 팀들의 리포중 활성화된 리포가 있길래 무심코 눌렀더니
여기로 왔네요... ㅎㅎ

다들 잘 지내시나요?!?

**Comment by jjerry-k** [comment]
잘 지내시죠....?

**Comment by CoodingPenguin** [comment]
@keeprainy @jjerry-k 오랜만입니당ㅠㅠㅠㅠ 그럭저럭 지내는 중이에용ㅠㅠㅠㅠ

**Comment by opijae** [comment]
아니 이런 누추한 곳에 귀한분들이...

**Comment by keeprainy** [comment]
다들 반갑습니다 ㅎㅎ
이 Repo 가 활성화되어있길래 그냥 이슈한번 올려보았습니다 ㅋㅋ
여기서 매주 일요일마다 LeetCode 푸시는 건가요???

**Comment by CoodingPenguin** [comment]
@keeprainy 네넹 지금은 다들 바쁘셔서 매주 리트코드 4개 풀고 PR 날리고 있어용

**Comment by CoodingPenguin** [comment]
@keeprainy 앗ㅠㅠ 첫 주에 시도했다가 잘 안 되서 일주일에 4문제로 바꿨습니당ㅠㅠ

**Comment by keeprainy** [comment]
@CoodingPenguin ㅠㅠ 그럼 저도 LeetCode 풀고 올려도 되나요???
(그리고 저 GitHub 펭귄님처럼 한번 꾸며봤습니다 ㅋㅋ)

**Comment by CoodingPenguin** [comment]
@keeprainy 넵! 가능합니다! (오옹 구글 공룡게임도 있네용ㅋㅋㅋㅋ👍)
